- name: Forward Networks Snapshots
  hosts: localhost
  vars_files:
    - forward-uri.properties

  tasks:

    - name: get Snapshots for a given Network id
      uri:
        url: https://{{base_url}}/api/networks/{{network_id}}/snapshots
        method: GET
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: snapshots_output
