- name: Forward Networks Checks
  hosts: localhost
  vars_files:
    - forward-uri.properties

  tasks:

    - name: get Checks for the given snapshot id
      uri:
        url: https://{{base_url}}/api/snapshots/{{snapshotId}}/checks
        method: GET
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: checks_output
