- name: Forward Networks Networks
  hosts: localhost
  vars_files:
    - forward-uri.properties

  tasks:

    - name: get all Networks from the Forward Networks platform
      uri:
        url: https://{{base_url}}/api/networks
        method: GET
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: networks_output
